/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface AccountTransfers {
  amount_cents: bigint;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  from_account_id: string;
  id: Generated<string>;
  occurred_on: string;
  tenant_id: string;
  to_account_id: string;
}

export interface AcquisitionCosts {
  amount_cents: bigint;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string;
  id: Generated<string>;
  lot_id: string;
  occurred_on: string;
  party_id: string | null;
  tenant_id: string;
  title_id: string | null;
  to_cogs_cents: bigint;
  to_inventory_cents: bigint;
}

export interface Attachments {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  height: number | null;
  id: Generated<string>;
  is_public: Generated<boolean>;
  mime: string;
  original_name: string | null;
  owner_id: string | null;
  owner_type: string;
  sha256: string;
  size_bytes: bigint;
  storage_key: string;
  tenant_id: string;
  width: number | null;
}

export interface AuditEvents {
  action: string;
  created_at: Generated<Timestamp>;
  data: Generated<Json>;
  entity: string;
  entity_id: string | null;
  id: Generated<bigint>;
  request_id: string | null;
  tenant_id: string;
  user_id: string | null;
}

export interface BillingInvoices {
  amount_cents: bigint;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  due_date: string;
  id: Generated<string>;
  notes: string | null;
  paid_at: Timestamp | null;
  period_end: string;
  period_start: string;
  provider: Generated<string>;
  provider_invoice_id: string | null;
  status: Generated<string>;
  subscription_id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CashMovements {
  account_id: string;
  amount_cents: bigint;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  direction: string;
  id: Generated<string>;
  kind: string;
  occurred_on: string;
  origin_id: string | null;
  origin_type: string;
  reversal_of: string | null;
  tenant_id: string;
}

export interface CashSessions {
  account_id: string;
  closed_at: Timestamp | null;
  closed_by: string | null;
  counted_cents: bigint | null;
  difference_cents: bigint | null;
  expected_cents: bigint | null;
  id: Generated<string>;
  justification: string | null;
  opened_at: Generated<Timestamp>;
  opened_by: string | null;
  opening_counted_cents: bigint;
  tenant_id: string;
}

export interface CatalogEvents {
  catalog_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<bigint>;
  kind: string;
  tenant_id: string;
  variant_id: string | null;
}

export interface CatalogItems {
  catalog_id: string;
  position: Generated<number>;
  tenant_id: string;
  variant_id: string;
}

export interface Catalogs {
  accept_orders: Generated<boolean>;
  contact_whatsapp: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  published: Generated<boolean>;
  published_at: Timestamp | null;
  show_prices: Generated<boolean>;
  slug: string;
  tenant_id: string;
  theme: Generated<Json>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Categories {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface DailyStockSnapshots {
  cost_cents: bigint;
  physical_qty: number;
  snapshot_date: string;
  tenant_id: string;
  variant_id: string;
}

export interface Documents {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  doc_type: string;
  generated_at: Timestamp | null;
  id: Generated<string>;
  last_error: string | null;
  number: bigint;
  sha256: string | null;
  snapshot: Json;
  source_id: string;
  source_type: string;
  status: Generated<string>;
  storage_key: string | null;
  template_version: string;
  tenant_id: string;
}

export interface DocumentSequences {
  doc_type: string;
  next_number: Generated<bigint>;
  tenant_id: string;
}

export interface ExpenseCategories {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  tenant_id: string;
}

export interface Expenses {
  amount_cents: bigint;
  cancel_reason: string | null;
  canceled_at: Timestamp | null;
  category_id: string | null;
  competence_date: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string;
  id: Generated<string>;
  kind: Generated<string>;
  notes: string | null;
  party_id: string | null;
  recurring_id: string | null;
  source_id: string | null;
  source_type: string | null;
  status: Generated<string>;
  tenant_id: string;
  title_id: string | null;
}

export interface FinancialAccounts {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  name: string;
  status: Generated<string>;
  tenant_id: string;
}

export interface FinancialPeriods {
  closed_at: Timestamp | null;
  closed_by: string | null;
  period: string;
  reason: string | null;
  reopened_at: Timestamp | null;
  reopened_by: string | null;
  status: string;
  tenant_id: string;
}

export interface FinancialTitles {
  balance_cents: bigint;
  cancel_reason: string | null;
  canceled_at: Timestamp | null;
  category: string | null;
  competence_date: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string;
  direction: string;
  due_date: string;
  id: Generated<string>;
  installment_count: Generated<number>;
  installment_number: Generated<number>;
  origin_id: string | null;
  origin_type: string;
  original_cents: bigint;
  party_id: string | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface GoodsReceiptItems {
  cost_cents: bigint;
  destination: Generated<string>;
  id: Generated<string>;
  lot_id: string | null;
  purchase_item_id: string;
  quantity: number;
  receipt_id: string;
  tenant_id: string;
  unit_id: string | null;
}

export interface GoodsReceipts {
  created_by: string | null;
  id: Generated<string>;
  notes: string | null;
  purchase_id: string;
  received_at: Generated<Timestamp>;
  tenant_id: string;
}

export interface HelpArticles {
  body: string;
  category: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  published: Generated<boolean>;
  reading_minutes: Generated<number>;
  slug: string;
  summary: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  key: string;
  operation: string;
  request_hash: string;
  response: Json | null;
  status_code: number | null;
  tenant_id: string;
}

export interface InventoryCountItems {
  count_id: string;
  counted_qty: number;
  expected_qty: number;
  id: Generated<string>;
  tenant_id: string;
  variant_id: string;
}

export interface InventoryCounts {
  confirmed_at: Timestamp | null;
  confirmed_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  location_id: string;
  notes: string | null;
  status: Generated<string>;
  tenant_id: string;
}

export interface InventoryLots {
  cost_received_cents: bigint;
  cost_remaining_cents: bigint;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  location_id: string;
  qty_received: number;
  qty_remaining: number;
  received_at: Generated<Timestamp>;
  source_id: string | null;
  source_type: string;
  status: Generated<string>;
  tenant_id: string;
  unit_id: string | null;
  variant_id: string;
}

export interface InventoryUnits {
  accessories: string | null;
  battery_health_pct: number | null;
  checklist: Generated<Json>;
  condition: string | null;
  created_at: Generated<Timestamp>;
  current_lot_id: string | null;
  defects: string | null;
  id: Generated<string>;
  internal_code: string;
  location_id: string;
  notes: string | null;
  status: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  variant_id: string;
  version: Generated<number>;
}

export interface Invites {
  accepted_at: Timestamp | null;
  accepted_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  role: string;
  tenant_id: string;
  token_hash: string;
}

export interface Locations {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_default: Generated<boolean>;
  name: string;
  tenant_id: string;
}

export interface MemberDirectory {
  created_at: Timestamp | null;
  discount_limit_bps: number | null;
  email: string | null;
  grants: string[] | null;
  membership_id: string | null;
  name: string | null;
  revokes: string[] | null;
  role: string | null;
  status: string | null;
  tenant_id: string | null;
  user_id: string | null;
}

export interface Memberships {
  created_at: Generated<Timestamp>;
  discount_limit_bps: Generated<number>;
  grants: Generated<string[]>;
  id: Generated<string>;
  revokes: Generated<string[]>;
  role: string;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Notifications {
  body: string | null;
  created_at: Generated<Timestamp>;
  dedupe_key: string | null;
  id: Generated<string>;
  kind: string;
  link: string | null;
  read_at: Timestamp | null;
  severity: Generated<string>;
  tenant_id: string;
  title: string;
  user_id: string | null;
}

export interface OffsetAllocations {
  amount_cents: bigint;
  id: Generated<string>;
  offset_id: string;
  tenant_id: string;
  title_id: string;
}

export interface Offsets {
  amount_cents: bigint;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  origin_id: string | null;
  origin_type: string;
  party_id: string;
  reversal_of: string | null;
  tenant_id: string;
}

export interface OutboxEvents {
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_error: string | null;
  locked_until: Timestamp | null;
  payload: Generated<Json>;
  processed_at: Timestamp | null;
  status: Generated<string>;
  tenant_id: string;
  type: string;
}

export interface Parties {
  address: Generated<Json>;
  city: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  document: string | null;
  document_normalized: string | null;
  email: string | null;
  id: Generated<string>;
  is_customer: Generated<boolean>;
  is_supplier: Generated<boolean>;
  name: string;
  notes: string | null;
  person_type: Generated<string>;
  phone: string | null;
  phone_normalized: string | null;
  search_text: Generated<string>;
  state: string | null;
  status: Generated<string>;
  tenant_id: string;
  trade_name: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PaymentMethods {
  account_id: string | null;
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  fee_bps: Generated<number>;
  id: Generated<string>;
  installment_fee_bps: Generated<Json>;
  kind: string;
  name: string;
  settlement_days: Generated<number>;
  tenant_id: string;
}

export interface Plans {
  active: Generated<boolean>;
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string;
  public: Generated<boolean>;
  sort_order: Generated<number>;
}

export interface PlanVersions {
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  features: Generated<string[]>;
  id: Generated<string>;
  limits: Generated<Json>;
  plan_id: string;
  price_monthly_cents: bigint;
  price_yearly_cents: bigint | null;
  trial_days: Generated<number>;
  valid_from: Generated<Timestamp>;
  valid_to: Timestamp | null;
  version: number;
}

export interface PlatformAdmins {
  created_at: Generated<Timestamp>;
  role: Generated<string>;
  user_id: string;
}

export interface PlatformAudit {
  action: string;
  admin_user_id: string;
  created_at: Generated<Timestamp>;
  data: Generated<Json>;
  id: Generated<bigint>;
  reason: string;
  tenant_id: string | null;
}

export interface ProductImages {
  attachment_id: string;
  position: Generated<number>;
  product_id: string;
  tenant_id: string;
}

export interface Products {
  brand: string | null;
  category_id: string | null;
  condition_default: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  identifier_kinds: Generated<string[]>;
  kind: Generated<string>;
  name: string;
  search_text: Generated<string>;
  status: Generated<string>;
  tenant_id: string;
  tracking: Generated<string>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  warranty_days: Generated<number>;
}

export interface ProductVariants {
  attributes: Generated<Json>;
  barcode: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_default: Generated<boolean>;
  label: Generated<string>;
  min_stock: Generated<number>;
  product_id: string;
  retail_price_cents: Generated<bigint>;
  sku: string;
  status: Generated<string>;
  suggested_price_cents: bigint | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  wholesale_min_qty: number | null;
  wholesale_price_cents: bigint | null;
}

export interface PublicOrderItems {
  description: string;
  id: Generated<string>;
  order_id: string;
  quantity: number;
  tenant_id: string;
  unit_price_cents: bigint;
  variant_id: string;
}

export interface PublicOrders {
  catalog_id: string;
  contact_name: string;
  contact_phone: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  notes: string | null;
  number: bigint;
  reservation_expires_at: Timestamp | null;
  sale_id: string | null;
  status: Generated<string>;
  tenant_id: string;
  total_cents: bigint;
  updated_at: Generated<Timestamp>;
}

export interface PurchaseItems {
  description: string;
  discount_cents: Generated<bigint>;
  discount_share_cents: Generated<bigint>;
  extra_share_cents: Generated<bigint>;
  id: Generated<string>;
  landed_cost_cents: Generated<bigint>;
  position: number;
  purchase_id: string;
  quantity: number;
  received_cost_cents: Generated<bigint>;
  received_qty: Generated<number>;
  tenant_id: string;
  unit_cost_cents: bigint;
  unit_specs: Generated<Json>;
  variant_id: string;
}

export interface Purchases {
  approved_at: Timestamp | null;
  cancel_reason: string | null;
  canceled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  discount_cents: Generated<bigint>;
  extra_costs_cents: Generated<bigint>;
  id: Generated<string>;
  items_cents: Generated<bigint>;
  notes: string | null;
  number: bigint | null;
  origin: Generated<string>;
  payment_terms: Generated<Json>;
  purchase_date: string;
  status: Generated<string>;
  supplier_id: string;
  tenant_id: string;
  total_cents: Generated<bigint>;
  trade_id: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface RecurringExpenses {
  active: Generated<boolean>;
  amount_cents: bigint;
  category_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  day_of_month: number;
  description: string;
  id: Generated<string>;
  last_generated_period: string | null;
  party_id: string | null;
  tenant_id: string;
}

export interface ReferralCodes {
  code: string;
  created_at: Generated<Timestamp>;
  tenant_id: string;
}

export interface Referrals {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  referred_tenant_id: string;
  referrer_tenant_id: string;
  status: Generated<string>;
}

export interface ReportJobs {
  created_at: Generated<Timestamp>;
  error: string | null;
  expires_at: Timestamp | null;
  filters: Generated<Json>;
  finished_at: Timestamp | null;
  format: string;
  id: Generated<string>;
  kind: string;
  requested_by: string | null;
  row_count: number | null;
  status: Generated<string>;
  storage_key: string | null;
  tenant_id: string;
}

export interface Reservations {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  location_id: string;
  quantity: number;
  source_id: string;
  source_type: string;
  status: Generated<string>;
  tenant_id: string;
  unit_id: string | null;
  updated_at: Generated<Timestamp>;
  variant_id: string;
}

export interface ReturnItems {
  cost_cents: bigint;
  id: Generated<string>;
  lot_id: string | null;
  quantity: number;
  return_id: string;
  revenue_cents: bigint;
  sale_item_id: string;
  tenant_id: string;
  unit_id: string | null;
}

export interface Returns {
  cost_cents: bigint;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  kind: Generated<string>;
  number: bigint;
  reason: string;
  reduced_balance_cents: Generated<bigint>;
  refund_cents: Generated<bigint>;
  refund_title_id: string | null;
  revenue_cents: bigint;
  sale_id: string;
  store_credit_cents: Generated<bigint>;
  tenant_id: string;
}

export interface SaleCostAllocations {
  cost_cents: bigint;
  id: Generated<string>;
  lot_id: string;
  quantity: number;
  returned_cost_cents: Generated<bigint>;
  returned_qty: Generated<number>;
  sale_item_id: string;
  tenant_id: string;
  unit_id: string | null;
}

export interface SaleItems {
  cost_cents: Generated<bigint>;
  description: string;
  gross_cents: bigint;
  id: Generated<string>;
  line_discount_cents: Generated<bigint>;
  order_discount_share_cents: Generated<bigint>;
  position: number;
  product_kind: string;
  quantity: number;
  returned_cost_cents: Generated<bigint>;
  returned_qty: Generated<number>;
  returned_revenue_cents: Generated<bigint>;
  sale_id: string;
  shipping_share_cents: Generated<bigint>;
  sku: string;
  tenant_id: string;
  total_cents: bigint;
  unit_id: string | null;
  unit_price_cents: bigint;
  variant_id: string;
}

export interface SalePayments {
  account_id: string | null;
  amount_cents: bigint;
  fee_bps: Generated<number>;
  fee_cents: Generated<bigint>;
  first_due_date: string | null;
  id: Generated<string>;
  installments: Generated<number>;
  kind: string;
  method_name: string;
  payment_method_id: string | null;
  position: number;
  sale_id: string;
  settled_now: Generated<boolean>;
  tenant_id: string;
}

export interface Sales {
  cancel_reason: string | null;
  canceled_at: Timestamp | null;
  channel_commission_bps: Generated<number>;
  channel_cost_cents: Generated<bigint>;
  channel_id: string | null;
  confirmed_at: Timestamp | null;
  cost_total_cents: Generated<bigint>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string | null;
  discount_approved_by: string | null;
  discount_cents: Generated<bigint>;
  draft_payload: Generated<Json>;
  fees_total_cents: Generated<bigint>;
  id: Generated<string>;
  notes: string | null;
  number: bigint | null;
  origin: Generated<string>;
  returned_cost_cents: Generated<bigint>;
  returned_revenue_cents: Generated<bigint>;
  sale_date: string;
  seller_user_id: string | null;
  shipping_cents: Generated<bigint>;
  status: Generated<string>;
  subtotal_cents: Generated<bigint>;
  tenant_id: string;
  total_cents: Generated<bigint>;
  trade_id: string | null;
  updated_at: Generated<Timestamp>;
  valid_until: string | null;
  version: Generated<number>;
}

export interface SalesChannels {
  active: Generated<boolean>;
  commission_bps: Generated<number>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  tenant_id: string;
}

export interface ServiceOrders {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  due_date: string | null;
  id: Generated<string>;
  number: bigint;
  party_id: string | null;
  price_cents: Generated<bigint>;
  sale_id: string | null;
  status: Generated<string>;
  tenant_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface SettlementAllocations {
  amount_cents: bigint;
  id: Generated<string>;
  settlement_id: string;
  tenant_id: string;
  title_id: string;
}

export interface Settlements {
  account_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  direction: string;
  fee_cents: Generated<bigint>;
  gross_cents: bigint;
  id: Generated<string>;
  method: string;
  net_cents: bigint;
  notes: string | null;
  party_id: string | null;
  reference: string | null;
  reversal_of: string | null;
  reversal_reason: string | null;
  settled_on: string;
  tenant_id: string;
}

export interface StockBalances {
  inspection: Generated<number>;
  location_id: string;
  on_hand: Generated<number>;
  reserved: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  variant_id: string;
  version: Generated<bigint>;
}

export interface StockMovements {
  bucket: Generated<string>;
  cost_cents: Generated<bigint>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  direction: string;
  id: Generated<string>;
  kind: string;
  location_id: string;
  lot_id: string | null;
  physical_after: number;
  quantity: number;
  reason: string | null;
  reversal_of: string | null;
  source_id: string | null;
  source_type: string;
  tenant_id: string;
  unit_id: string | null;
  variant_id: string;
}

export interface StoreCreditBalances {
  balance_cents: Generated<bigint>;
  party_id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface StoreCreditEntries {
  amount_cents: bigint;
  balance_after_cents: bigint;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  expires_on: string | null;
  id: Generated<string>;
  kind: string;
  origin_id: string | null;
  origin_type: string;
  party_id: string;
  reason: string | null;
  tenant_id: string;
  title_id: string | null;
}

export interface SubscriptionEvents {
  actor: string | null;
  created_at: Generated<Timestamp>;
  from_status: string | null;
  id: Generated<string>;
  idempotency_key: string | null;
  reason: string;
  subscription_id: string;
  tenant_id: string;
  to_status: string;
}

export interface Subscriptions {
  billing_interval: Generated<string>;
  cancel_at_period_end: Generated<boolean>;
  canceled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  current_period_end: Timestamp;
  current_period_start: Timestamp;
  grace_days: Generated<number>;
  id: Generated<string>;
  plan_version_id: string;
  provider: Generated<string>;
  provider_customer_id: string | null;
  provider_subscription_id: string | null;
  status: string;
  tenant_id: string;
  trial_ends_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface Tenants {
  address: Generated<Json>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: Generated<string>;
  document: string | null;
  email: string | null;
  id: Generated<string>;
  legal_name: string | null;
  name: string;
  onboarding: Generated<Json>;
  phone: string | null;
  settings: Generated<Json>;
  slug: string;
  status: Generated<string>;
  status_reason: string | null;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface TitleAdjustments {
  amount_cents: bigint;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  kind: string;
  origin_id: string | null;
  origin_type: string;
  reason: string | null;
  tenant_id: string;
  title_id: string;
}

export interface Trades {
  confirmed_at: Generated<Timestamp>;
  created_by: string | null;
  difference_cents: bigint;
  difference_policy: string;
  id: Generated<string>;
  notes: string | null;
  number: bigint;
  offset_cents: bigint;
  offset_id: string | null;
  party_id: string;
  purchase_id: string;
  purchase_total_cents: bigint;
  reversal_reason: string | null;
  reversed_at: Timestamp | null;
  sale_id: string;
  sale_total_cents: bigint;
  status: Generated<string>;
  tenant_id: string;
}

export interface TradeValuations {
  agreed_cents: bigint;
  checklist: Generated<Json>;
  condition: string | null;
  destination: Generated<string>;
  estimated_extra_cost_cents: Generated<bigint>;
  id: Generated<string>;
  identifiers: Generated<Json>;
  notes: string | null;
  position: number;
  purchase_item_id: string;
  suggested_price_cents: bigint | null;
  tenant_id: string;
  trade_id: string;
  unit_id: string | null;
  variant_id: string;
}

export interface TrialClaims {
  created_at: Generated<Timestamp>;
  tenant_id: string;
  user_id: string;
}

export interface TwoFactor {
  backupCodes: string;
  failedVerificationCount: number | null;
  id: string;
  lockedUntil: Timestamp | null;
  secret: string;
  userId: string;
  verified: boolean | null;
}

export interface UnitIdentifiers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  normalized: string;
  tenant_id: string;
  unit_id: string;
  value: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  twoFactorEnabled: boolean | null;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface WarrantyCases {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string;
  id: Generated<string>;
  number: bigint;
  party_id: string | null;
  resolution: string | null;
  sale_id: string;
  sale_item_id: string | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  warranty_terms_snapshot: string | null;
}

export interface WebhookEvents {
  event_type: string;
  external_id: string;
  id: Generated<string>;
  payload: Json;
  processed_at: Timestamp | null;
  provider: string;
  received_at: Generated<Timestamp>;
  result: string | null;
  signature_valid: boolean;
}

export interface DB {
  account: Account;
  account_transfers: AccountTransfers;
  acquisition_costs: AcquisitionCosts;
  attachments: Attachments;
  audit_events: AuditEvents;
  billing_invoices: BillingInvoices;
  cash_movements: CashMovements;
  cash_sessions: CashSessions;
  catalog_events: CatalogEvents;
  catalog_items: CatalogItems;
  catalogs: Catalogs;
  categories: Categories;
  daily_stock_snapshots: DailyStockSnapshots;
  document_sequences: DocumentSequences;
  documents: Documents;
  expense_categories: ExpenseCategories;
  expenses: Expenses;
  financial_accounts: FinancialAccounts;
  financial_periods: FinancialPeriods;
  financial_titles: FinancialTitles;
  goods_receipt_items: GoodsReceiptItems;
  goods_receipts: GoodsReceipts;
  help_articles: HelpArticles;
  idempotency_keys: IdempotencyKeys;
  inventory_count_items: InventoryCountItems;
  inventory_counts: InventoryCounts;
  inventory_lots: InventoryLots;
  inventory_units: InventoryUnits;
  invites: Invites;
  locations: Locations;
  member_directory: MemberDirectory;
  memberships: Memberships;
  notifications: Notifications;
  offset_allocations: OffsetAllocations;
  offsets: Offsets;
  outbox_events: OutboxEvents;
  parties: Parties;
  payment_methods: PaymentMethods;
  plan_versions: PlanVersions;
  plans: Plans;
  platform_admins: PlatformAdmins;
  platform_audit: PlatformAudit;
  product_images: ProductImages;
  product_variants: ProductVariants;
  products: Products;
  public_order_items: PublicOrderItems;
  public_orders: PublicOrders;
  purchase_items: PurchaseItems;
  purchases: Purchases;
  recurring_expenses: RecurringExpenses;
  referral_codes: ReferralCodes;
  referrals: Referrals;
  report_jobs: ReportJobs;
  reservations: Reservations;
  return_items: ReturnItems;
  returns: Returns;
  sale_cost_allocations: SaleCostAllocations;
  sale_items: SaleItems;
  sale_payments: SalePayments;
  sales: Sales;
  sales_channels: SalesChannels;
  service_orders: ServiceOrders;
  session: Session;
  settlement_allocations: SettlementAllocations;
  settlements: Settlements;
  stock_balances: StockBalances;
  stock_movements: StockMovements;
  store_credit_balances: StoreCreditBalances;
  store_credit_entries: StoreCreditEntries;
  subscription_events: SubscriptionEvents;
  subscriptions: Subscriptions;
  tenants: Tenants;
  title_adjustments: TitleAdjustments;
  trade_valuations: TradeValuations;
  trades: Trades;
  trial_claims: TrialClaims;
  twoFactor: TwoFactor;
  unit_identifiers: UnitIdentifiers;
  user: User;
  verification: Verification;
  warranty_cases: WarrantyCases;
  webhook_events: WebhookEvents;
}
