-- Conteúdo próprio da central de ajuda (texto original, descreve o comportamento deste sistema).
-- Idempotente por slug; edições futuras entram em novas migrações ou pelo papel da plataforma.
insert into help_articles (slug, category, title, summary, body, published, reading_minutes) values
('primeira-configuracao', 'primeiros-passos', 'Primeira configuração da empresa',
 'Contas, formas de pagamento, equipe e o que conferir antes da primeira venda.',
 E'Ao criar a empresa, o sistema já cadastra um caixa, uma conta bancária, as formas de pagamento mais comuns e o canal "Loja".\n\n1. Em Configurações › Pagamentos, revise as taxas de cartão e o prazo de recebimento de cada forma. A taxa é lançada como despesa financeira quando o valor cai na conta, não no momento da venda.\n2. Em Configurações › Empresa, preencha documento, endereço e os termos de garantia. Esses dados aparecem nos recibos em PDF.\n3. Em Configurações › Equipe, convide pessoas com o papel adequado. Vendedores não veem custo nem lucro.\n4. Cadastre produtos ou registre uma compra: o estoque só existe depois de uma entrada (compra, troca ou ajuste com motivo).',
 true, 3),
('como-registrar-venda', 'vendas', 'Como registrar uma venda',
 'Itens, desconto, formas de pagamento e o que acontece no estoque e no financeiro.',
 E'Em Vendas › Nova venda, busque o produto pelo nome, SKU ou IMEI. Para aparelhos com número de série, escolha a unidade exata vendida.\n\nA soma das formas de pagamento precisa ser igual ao total. Você pode combinar, por exemplo, Pix de entrada e o restante no crediário em parcelas.\n\nAo confirmar:\n- o estoque baixa pelo custo do lote mais antigo (ou pelo custo da unidade, se for serializada);\n- pagamentos à vista entram no caixa ou na conta;\n- crediário e cartão a receber viram contas a receber com vencimento.\n\nSe a internet cair durante a confirmação, repita o envio: a venda não é duplicada.',
 true, 3),
('entendendo-a-troca', 'trocas', 'Entendendo a troca com diferença',
 'Como o sistema registra o aparelho que sai, o que entra e a diferença paga.',
 E'Uma troca é registrada como três partes ligadas:\n\n1. Venda do produto que sai da loja, pelo preço combinado.\n2. Compra do produto que o cliente entrega, pelo valor avaliado. Esse valor vira o custo do item recebido.\n3. Compensação: o menor dos dois valores é abatido entre a conta a receber e a conta a pagar. Nenhum dinheiro fictício entra no caixa.\n\nSó a diferença movimenta dinheiro: se o cliente paga, entra no caixa; se a loja paga, sai. A diferença também pode virar crédito da loja ou ficar em aberto.\n\nExemplo: aparelho vendido por R$ 2.000 e usado avaliado em R$ 1.500. A compensação é de R$ 1.500 e o cliente paga R$ 500. O usado entra no estoque com custo de R$ 1.500 (em inspeção, até ser liberado para venda).',
 true, 4),
('desfazer-troca', 'trocas', 'Desfazer uma troca',
 'Quando é possível reverter e o que o sistema faz com estoque e dinheiro.',
 E'Uma troca pode ser revertida enquanto o produto recebido ainda está na loja. A reversão devolve o item vendido ao estoque, retira o item recebido e desfaz a compensação.\n\nSe dinheiro já transitou, o sistema gera o reembolso correspondente como conta a pagar ou a receber, para você registrar quando acontecer. Nada é apagado: a operação original e a reversão ficam no histórico.\n\nSe o produto recebido já foi vendido, a troca não pode ser simplesmente cancelada. Nesse caso registre uma devolução da venda ou um ajuste com motivo.',
 true, 2),
('estoque-lotes-e-inspecao', 'estoque', 'Lotes, custo e itens em inspeção',
 'Por que o custo não muda sozinho e para que serve a inspeção.',
 E'Cada entrada cria um lote com custo próprio. A venda consome primeiro o lote mais antigo. Por isso, mudar o preço de custo no cadastro não altera vendas passadas.\n\nItens recebidos em troca ou devolvidos ficam "em inspeção": aparecem no estoque físico, mas não estão disponíveis para venda. Libere em Estoque depois de conferir o aparelho. Se houver gasto com reparo, lance como custo de aquisição do item.\n\nAjustes de estoque sempre pedem motivo e ficam na auditoria.',
 true, 3),
('contas-a-receber', 'financeiro', 'Recebimentos parciais e estornos',
 'Como baixar parcelas, corrigir um recebimento lançado errado e ver o saldo real.',
 E'Em Financeiro › A receber, use "Receber" para registrar um pagamento total ou parcial. O saldo da conta diminui e o dinheiro entra na conta escolhida.\n\nLançou errado? Use "Estornar" no recebimento. O lançamento original continua visível, o estorno aparece ao lado e o saldo volta ao que era. Isso mantém o histórico confiável para conferência.\n\nTransferências entre contas e aportes do dono não contam como receita.',
 true, 3),
('resultado-e-lucro', 'financeiro', 'Como o lucro é calculado',
 'Receita, custo das mercadorias, taxas e despesas no relatório de resultado.',
 E'O relatório de resultado usa as mesmas fórmulas do painel:\n\n- Receita líquida = vendas − descontos − devoluções.\n- Custo das mercadorias vendidas = custo histórico dos itens que saíram (lote ou unidade).\n- Lucro bruto = receita líquida − custo das mercadorias.\n- Resultado operacional = lucro bruto − taxas de pagamento − despesas do período.\n\nO resultado é gerencial: não substitui a apuração fiscal ou contábil.',
 true, 3),
('seguranca-da-conta', 'seguranca', 'Proteja sua conta com verificação em duas etapas',
 'Ative o código do aplicativo autenticador e guarde os códigos de recuperação.',
 E'Em Configurações › Plano e segurança, confirme sua senha e ative a verificação em duas etapas. Adicione a chave em um aplicativo autenticador e digite o código de 6 dígitos para concluir.\n\nGuarde os códigos de recuperação fora do celular. Eles permitem entrar se você perder o aparelho.\n\nSe suspeitar de acesso indevido, use "Encerrar sessões em outros dispositivos" e troque a senha.',
 true, 2)
on conflict (slug) do nothing;
